### ISSUE TITLE
Asana MCP doesn't work with Bedrock

### ISSUE THREAD

**Issue by angiejones** [block/goose#1804]
**Describe the bug**

When running a session with the [Asana MCP server](https://github.com/roychri/mcp-server-asana) enabled and an Amazon Bedrock model, the following error occurs

```
Ran into this error: Request failed: Request failed with status: 400 Bad Request. Message: {"external_model_provider":"amazon-bedrock","external_model_error":{"message":"tools.39.input_schema.properties: Property keys should match pattern '^[a-zA-Z0-9_-]{1,64}$'"}}.
```

Changing the model to GPT-4o works.

@baxen says "we should just do a conversion of some kind if it won't work on bedrock"

**To Reproduce**
1. Add Asana extension w/ valid Asana Access Token
```
goose://extension?cmd=npx&arg=-y&arg=%40roychri%2Fmcp-server-asana&id=asana&name=Asana&description=enable%20task%20automation%2C%20project%20tracking%2C%20and%20team%20collaboration&env=ASANA_ACCESS_TOKEN%3DAsana%20Access%20Token
```
2. Change Provider to Amazon Bedrock
3. Start session and enter any prompt

**Comment by zakiali** [comment]
If you use the beta version of the mcp, this should work. The issue is that the current release has [function parameters](https://github.com/roychri/mcp-server-asana/commit/579ac7c4bd20768c8e926945c10b6977eec419f9) with dots ('.') in their name. There was an update to handle this, but it's only released in beta for now. 

To install use the following block: 
```  
asana:
    args:
    - -y
    - '@roychri/mcp-server-asana@beta'
    cmd: npx
    description: null
    enabled: true
    envs:
      ASANA_ACCESS_TOKEN: abcd
    name: asana
    timeout: 300
    type: stdio
```
