### ISSUE TITLE
Allow/deny list for developer__shell commands

### ISSUE THREAD

**Issue by mclarke47** [block/goose#2637]
**Please explain the motivation behind the feature request.**
Since the actions taken within the models are not deterministic, actions could be taken that pose a security risk. Such as publishing proprietary/sensitive information to a public source with `git` / `curl`. This is especially risky with the `developer__shell` extension as any command on the local machine could be invoked.

**Describe the solution you'd like**
Additional options to restrict the actions/executables that the `developer__shell` extension can take, for example a section of the extension in the `config.yaml`:

```yaml
extensions:
  developer:
    enabled: true
    allowed_executables: ["ls", "find", "'rg", "kubectl"]
    name: developer
    type: builtin
```

Potentially hooking the validation in [here](https://github.com/block/goose/blob/main/crates/goose-mcp/src/developer/mod.rs#L494)

**Describe alternatives you've considered**
An allowlist seems better since you might miss an important executable that you should exclude

```yaml
extensions:
  developer:
    enabled: true
    disallowed_executables: ["curl", "git", "kubectl"]
    name: developer
    type: builtin
```

**Additional context**
N/A

- [x] I have verified this does not duplicate an existing feature request
