### ISSUE TITLE
Goose gets confused about provider when env is used in addition to `goose config`

### ISSUE THREAD

**Issue by mikegehard-rise8** [block/goose#2646]
Goose asks me to select provider and model when configured with env vars

I am running Goose in a devcontainer to increase security using https://github.com/mikegehard/goose-devcontainer-feature. I am configuring Goose via env vars in an .env file to prevent me from having to reconfigure Goose on container rebuilds.

```
vscode ➜ /workspaces/XPai (main) $ env | grep GOOSE_     
GOOSE_PLANNER_PROVIDER=google
GOOSE_PROVIDER=google
GOOSE_PLANNER_MODEL=gemini-2.5-pro-preview-05-06
GOOSE_MODEL=gemini-2.5-flash-preview-05-20
vscode ➜ /workspaces/XPai (main) $ 
```
**To Reproduce**
1. Rebuild container
2. Type "goose" in terminal
3. Provider is selected correctly
4. It sees the Google API key in the env
5. It displays a list of models but the list is long so I have to scroll down to find the Gemini model I want. And if I select a different model, it still uses the one in the env var.

**Expected behavior**
I expect that since I have configured the model provider information via env vars then I wouldn't have to configure them again when I rebuild the model.

And if I do configure it in the UI, I would expect it to respect that choice.

**Screenshots**

**Please provide following information:**
 - **OS & Arch:** 
```
( O)> what os are you running?
─── shell | developer ──────────────────────────
command: uname -a

I am running on a Linux operating system. The kernel version is `6.12.13-200.fc41.aarch64`.
( O)> what distro of linux

─── shell | developer ──────────────────────────
command: cat /etc/os-release

I am running Ubuntu 22.04.5 LTS (Jammy Jellyfish).
( O)> 
```

 - **Interface:** CLI
 - **Version:** [e.g. v1.0.24]
 - **Extensions enabled:** 
```
GOOSE_PROVIDER: google
GOOSE_MODEL: gemini-2.5-pro-preview-05-06
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
/home/vscode/.config/goose/config.yaml (END)
```
 - **Provider & Model:** Google, env var says flash but config says pro and goose is using flash

```
vscode ➜ /workspaces/XPai (main) $ goose
starting session | provider: google model: gemini-2.5-flash-preview-05-20
    logging to /home/vscode/.local/share/goose/sessions/20250523_124210.jsonl
    working directory: /workspaces/XPai

Goose is running! Enter your instructions, or try asking what goose can do.

( O)> 
```

**Additional context**
