### ISSUE TITLE
Goose does not pick up an existing config file when running for the first time.

### ISSUE THREAD

**Issue by mikegehard-rise8** [block/goose#2649]
**Describe the bug**

Possibly related to https://github.com/block/goose/issues/2646?

I am running Goose in a devcontainer to increase security using https://github.com/mikegehard/goose-devcontainer-feature.

I am configuring Goose via a combination of env vars in an .env file and a config file to prevent me from having to reconfigure Goose on container rebuilds using `goose config`.

The .env file contains the API keys and the config file contains a copy of the goose config file that will be copied into the container.

When I rebuild the container, which simulates installing goose for the first time, when I run `goose` it asks me to configure the tool.

**To Reproduce**
1. Clear out running podman containers.
```
➜  XPai git:(main) ✗ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
➜  XPai git:(main) ✗ code .
```
2. Reopen container
3. Run `goose`
4. See config screen

**Expected behavior**
Goose starts normally as if it was not being run for the first time and I don't see the config screen.

**Screenshots**
```
vscode ➜ /workspaces/XPai (main) $ env | grep GOOGLE_
GOOGLE_API_KEY=<some API key>
vscode ➜ /workspaces/XPai (main) $ cat ~/.config/goose/config.yml 
# Goose configuration to be copied into the devcontainer
#API key set with GOOGLE_API_KEY in .env
GOOSE_PROVIDER: google
GOOSE_MODEL: gemini-2.5-flash-preview-05-20
GOOSE_PLANNER_PROVIDER: google
GOOSE_PLANNER_MODEL: gemini-2.5-pro-preview-03-25
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin%                                                                                                                        
vscode ➜ /workspaces/XPai (main) $ 
```

<img width="613" alt="Image" src="https://github.com/user-attachments/assets/0a3fd05e-eb1a-4d01-bccd-dff42c7e9cf4" />

**Please provide following information:**
 - **OS & Arch:** Linux 99570a01a99e 6.12.13-200.fc41.aarch64 Sat Feb  8 20:30:50 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
 - **Interface:** CLI
 - **Version:** 1.0.24
 - **Extensions enabled:** [e.g. Develoer]

**Additional context**
