### ISSUE TITLE
Goose LLM cannot use MCP tools

### ISSUE THREAD

**Issue by brianhuster** [block/goose#2672]
**Describe the bug**

I tried to prompt LLM to use tool, but it seems incapable to use it. This is the conversation I had with goose today. Note that the `mcp-wiki` extension is taken from https://block.github.io/goose/docs/tutorials/custom-extensions/
```markdown
─── read_resource | platform ──────────────────────────
extension_name: mcp-wiki
uri: ...


Execution failed: Could not read resource with uri: https://en.wikipedia.org/wiki/T%C3%B4_L%C3%A2m
It seems that the `mcp-wiki` extension was unable to fetch the resource at the given URL. This could be due to limitati
ons on accessing that specific resource from the extension.

If there's anything else you'd like me to assist with regarding this topic or a different approach you'd like me to att
( O)> Use the tool `read_wikipedia_article`

─── search_available_extensions | platform ──────────────────────────



It looks like I currently don't have access to a `read_wikipedia_article` tool, nor can I enable additional extensions 
to provide that capability. However, I can help you in other ways, such as guiding you to access the article directly o
n Wikipedia or perhaps summarizing related information if you're looking for specific details. Let me know!
```

**To Reproduce**
1. Use the following config.yaml
```yaml
extensions:
  mcp-wiki:
    args: []
    bundled: null
    cmd: mcp-wiki
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: mcp-wiki
    timeout: 300
    type: stdio
GOOSE_MODE: auto
GOOSE_MODEL: gpt-4o
GOOSE_PROVIDER: github_copilot
```

2. Follow step 1 to step 4 in https://block.github.io/goose/docs/tutorials/custom-extensions/ to create `mcp-wiki` extension
3. Open `goose` and prompt it with "Tell me about Tô Lâm, by using extension `mcp-wiki` to read this article `https://en.wikipedia.org/wiki/T%C3%B4_L%C3%A2m`"

**Expected behavior**
It should be able to use tool mcp-wiki
**Screenshots**

**Please provide following information:**
 - **OS & Arch:** [e.g. Ubuntu 22.04 x86]
 - **Interface:** [UI/CLI]
 - **Version:** [e.g. v1.0.2]
 - **Extensions enabled:** [e.g. Computer Controller, Figma]
 - **Provider & Model:** [e.g. Google - gemini-1.5-pro]

**Additional context**
