### ISSUE TITLE
Goose 1.0.24 fails with Gemini models

### ISSUE THREAD

**Issue by mikegehard-rise8** [block/goose#2792]
API error when using Gemini based models.

**To Reproduce**
1. Set Google Gemini as the model. Both *-05-06 and *-03-25 fail.
2. Try to execute a command as simple as "hello"
3. Get API error

**Expected behavior**
The API call returns.

**Screenshots**
```
vscode ➜ /workspaces/XPai (prompt-content-integration) $ goose
starting session | provider: google model: gemini-2.5-pro-preview-05-06
    logging to /home/vscode/.local/share/goose/sessions/20250605_151247.jsonl
    working directory: /workspaces/XPai

Goose is running! Enter your instructions, or try asking what goose can do.

( O)> hello
◐  Diving for answers...                                                                                                                    2025-06-05T15:12:51.630914Z ERROR goose::agents::agent: Error: Request failed: Request failed with status: 400 Bad Request. Message: * GenerateContentRequest.tools[0].function_declarations[0].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type

    at crates/goose/src/agents/agent.rs:527

Ran into this error: Request failed: Request failed with status: 400 Bad Request. Message: * GenerateContentRequest.tools[0].function_declarations[0].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type
.

Please retry if you think this is a transient or recoverable error.
( O)> 
```
```
vscode ➜ /workspaces/XPai (prompt-content-integration) $ goose
starting session | provider: google model: gemini-2.5-pro-preview-03-25
    logging to /home/vscode/.local/share/goose/sessions/20250605_151333.jsonl
    working directory: /workspaces/XPai

Goose is running! Enter your instructions, or try asking what goose can do.

( O)> hello
◐  Gathering computational momentum...                                                                                                      2025-06-05T15:13:38.223504Z ERROR goose::agents::agent: Error: Request failed: Request failed with status: 400 Bad Request. Message: * GenerateContentRequest.tools[0].function_declarations[11].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type

    at crates/goose/src/agents/agent.rs:527

Ran into this error: Request failed: Request failed with status: 400 Bad Request. Message: * GenerateContentRequest.tools[0].function_declarations[11].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type
.

Please retry if you think this is a transient or recoverable error.
( O)> 
```

**Please provide following information:**
 - **OS & Arch:** Ubuntu
 - **Interface:** CLI
 - **Version:** 1.0.24
 - **Extensions enabled:** Developer, Filesystem, Fetch
 - **Provider & Model:** Google Gemini pro *-05-06 and *-03-25

**Additional context**

**Comment by mikegehard-rise8** [comment]
```
GOOSE_MODEL: gemini-2.5-pro-preview-03-25
GOOSE_PLANNER_MODEL: gemini-2.5-pro-preview-03-25
GOOSE_PLANNER_PROVIDER: google
GOOSE_PROVIDER: google
extensions:
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  filesystem:
    args:
    - -y
    - '@modelcontextprotocol/server-filesystem'
    - .
    bundled: null
    cmd: npx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: filesystem
    timeout: 300
    type: stdio
  mcp-fetch:
    args:
    - mcp-server-fetch
    bundled: null
    cmd: uvx
    description: Basic MCP server to fetch web content
    enabled: true
    env_keys: []
    envs: {}
    name: mcp-fetch
    timeout: 300
    type: stdio
```
