### ISSUE TITLE
After 1.0.30 upgrade MCP fails with `Error invoking remote method 'get-binary-path'`

### ISSUE THREAD

**Issue by stefanprodan** [block/goose#3139]
**Describe the bug**

After 1.0.30 upgrade of the Desktop App on macOS all MCP Extensions are failing with:

```
Error invoking remote method 'get-binary-path': Error: Could not find npx binary in any of the expected locations: /Applications/Goose.app/Contents/Resources/bin/npx, /Applications/Goose.app/Contents/Resources/app.asar/resources/bin/npx
```

My MCP config that used to work in previous versions:

```yaml
  flux:
    args:
    - serve
    bundled: null
    cmd: /Users/stefanprodan/go/src/github.com/controlplaneio-fluxcd/flux-operator/bin/flux-operator-mcp
    description: Flux CD
    enabled: true
    env_keys:
    - KUBECONFIG
    envs: {}
    name: flux
    timeout: 300
    type: stdio
```

**Expected behavior**

Expected to search for `npx` in my PATH. Also why would npx be required if my MCP Server is a standalone Go binary?

**Please provide following information:**
 - **OS & Arch:** macOS arm64
 - **Interface:** UI
 - **Version:** 1.0.30
 - **Extensions enabled:** Developer
 - **Provider & Model:** any model

**Additional context**

- The desktop app was installed with `brew install --cask block-goose`
- npx is available `$ which npx /opt/homebrew/bin/npx`
