### ISSUE TITLE
Missing metadata in pyproject.toml

### ISSUE THREAD

**Issue by shirhatti** [block/goose#486]
The `pyproject.toml` files for both the `goose-ai` and `ai-exchange` packages are missing some common metadata fields. Would you be willing to add the following properties:

```toml
[project]
license = "Apache 2.0"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",  
]

[project.urls]
Changelog = "https://github.com/block/goose/blob/main/CHANGELOG.md"
Documentation = "https://block.github.io/goose/"
Homepage = "https://github.com/block/goose/"
Source = "https://github.com/block/goose/"
```

I'm not entirely familiar with conventions around [classifiers](https://pypi.org/classifiers/) but I presume there are a few more that'll be applicable.

Happy to submit a PR if needed!
